name: First workflow for Mercedes Benz

on: 
  push: 
    branches:
    - main
  schedule:
    - cron: "0 2 * * 1"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

        with: 
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
          browser: chrome
          version: latest
          record: true
          parallel: true # Runs test in parallel using settings above

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

