name: First workflow for Mercedes Benz

on: 
  push: 
    branches:
    - main
  schedule:
    - cron: "0 2 * * 1"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start app
        run: npm start &

      - name: Cypress run
        uses: cypress-io/github-action@v6

        with: 
          browser: chrome
          record: true
          parallel: true # Runs test in parallel using settings above

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

